In [2]:
print ("Hello World!")

Hello World!


In [3]:
mylist = [1,2,3]

In [4]:
mylist

[1, 2, 3]

In [5]:
import numpy as np 

In [6]:
# casting python list to an array 

arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
mymat = [[1,2,3],[4,5,6],[7,8,9]] 

In [9]:
mymat 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(mymat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# genereting an array using numPy 
# arange is a method like the python .range()
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# generating an array adding step size
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
# using some functions for specific types of arrays 
# ex >>> generating an array of all zeros 
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [14]:
# or generating an array of all zeros passing a tuple of the dimension you want 

np.zeros((4,3))        # 1ST num representing the num of ROWS, 2ND num reoresenting the num of COLUMNS 



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# ex >>> generating an array of all ones 
np.ones((3,4)) 


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [117]:
# ex >>> generating an array of number of points between a range 
# Similar to arrange but linspace, uses number of samples (instead of the step size).
# note it's 1D array, you can tell that, looking to the number of the brackets 
np.linspace(0,19,20)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [17]:
# ex >>> generating an identity metrix (2d square matrix of zeros, have a diagonal of ones.) 
# useful dealing wz linear algebra problems 

np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# ex >>> generating an array of random numbers (there are many ways to do that)
# generating a 1D array of random numbers from 0-1 
np.random.rand(30)

array([0.55319894, 0.33809475, 0.91707098, 0.03612855, 0.63619433,
       0.52606745, 0.33728641, 0.16505418, 0.43195846, 0.77983721,
       0.61684504, 0.91222937, 0.15496904, 0.96116774, 0.31122099,
       0.48612476, 0.75551774, 0.64791752, 0.95956898, 0.60373096,
       0.42568756, 0.02403526, 0.1196504 , 0.88990637, 0.3961599 ,
       0.10324926, 0.68130987, 0.87648631, 0.19883935, 0.95896629])

In [19]:
# generating a 2D array of random numbers from 0-1 
np.random.rand(5,5)


array([[0.80882464, 0.54731501, 0.99816312, 0.41454038, 0.18247834],
       [0.33432194, 0.83277875, 0.97136048, 0.2571986 , 0.14479118],
       [0.2134271 , 0.21882438, 0.77785477, 0.31858887, 0.65122412],
       [0.14568586, 0.96355943, 0.02557204, 0.62343481, 0.37786272],
       [0.5406423 , 0.33221298, 0.93499152, 0.60248027, 0.57767951]])

In [112]:
# generating an array of random int numbers passing low, high and size 

arr = np.random.randint(1,3,100)


In [122]:
arr2 = np.random.randint(1,3, size = (2,3))

In [121]:
arr2

array([1, 4])

In [113]:
arr

array([1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1,
       2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2,
       1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2,
       2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1])

In [114]:
# finding the location of the max value of an array
arr.argmax()

1

In [23]:
# some useful attributes and methods of an array
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr = np.random.randint(0,52,10)

In [26]:
ranarr

array([30,  8, 12, 14, 41, 45,  9, 10,  6, 31])

In [27]:
# get it sorted 
np.sort(ranarr)

array([ 6,  8,  9, 10, 12, 14, 30, 31, 41, 45])

In [28]:
# reshape method 
# attention the size of the arr should be enough for the asked new shape 
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr

array([30,  8, 12, 14, 41, 45,  9, 10,  6, 31])

In [30]:
# finding max or min values or location 
ranarr.max()

45

In [31]:
# finding the min value of an array
ranarr.min()

6

In [32]:
# finding the location of the max value of an array
ranarr.argmax()


5

In [33]:
# finding the location of the min value of an array
ranarr.argmin()


8

In [34]:
# know the shape of an array 
ranarr.shape 


(10,)

In [35]:
# reshape it and check again 
arr = arr.reshape(5,5)


In [36]:
arr.shape 

(5, 5)

In [115]:
arr

array([1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1,
       2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2,
       1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2,
       2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1])

In [37]:
# check the data type of an array 
arr.dtype 

dtype('int64')

In [38]:
# using random a lot? 
from numpy.random import randint 

In [39]:
randint(3,4)

3

NumPy Indexing and Selection 

In [40]:
# creating a sample array 
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# pick out one of the elements of an array 
# it looks a lot like indexing from a python list 
# basicly use brackets and slice notation
# type the variable name of the array itself and passing square brackets to get a single value at an index by passing a number 
# if we want the value at index 8, pass 8 and it will return back the value in 8th index 
arr[8]

8

In [43]:
# we can use slice notation
# passing the starting index and the stop index "[starting index number x : up to index number x]
arr[1:5]

array([1, 2, 3, 4])

In [44]:
# you can also remove the stop point or the start point to go ahead and indicate everything else in the array
# ex> everything from the beginning up to 6
# here is one way 1st way to get everyehing from the beginning up to 6 
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
# here is the same thing removing the start index number 
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [46]:
# or removing the stop index, indicate to get everything else in the array 
# don't forget 5 here is index 6 
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
# using numpy broadcast give the ability to broadcast that value to a slice.
# ex >> broadcast the value to first five elements to all be 100 
arr[0:5] = 100

In [48]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
# reset the array 
arr = np.arange(0,11)

In [50]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
# get a slice of an array in a varialbe 
slice_of_arr = arr[0:6]

In [52]:
slice_of_arr 

array([0, 1, 2, 3, 4, 5])

In [53]:
# let's broadcast this array and see what happens 
slice_of_arr[:] = 99

In [54]:
slice_of_arr 

array([99, 99, 99, 99, 99, 99])

In [55]:
arr 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
"""
So notice how that change also occurs in the original array
meaning the data is no copiedt, it's just a view of the original array.
The reason it does that is to avoid memory issues with very large arrays, 
meaning numPy is not going to automatically set copies of arrays.
If you actually want a copy and not a reference to the original array, 
which you can do is actually a specify copy.
"""

"\nSo notice how that change also occurs in the original array\nmeaning the data is no copiedt, it's just a view of the original array.\nThe reason it does that is to avoid memory issues with very large arrays, \nmeaning numPy is not going to automatically set copies of arrays.\nIf you actually want a copy and not a reference to the original array, \nwhich you can do is actually a specify copy.\n"

In [57]:
# so use the copy method to specifically indicate that I want a copy.
arr_copy = arr.copy()

In [58]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
# let's make a change on the copy and see 
arr_copy[:] = 100

In [60]:
arr_copy 

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [61]:
# check the orginal array
# the original array is not gonna be affected by the change.

arr 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### indexing 2D array 

In [62]:
# creating a 2D array or a matrix 

arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])  # don't forget using 2 brackets 

In [63]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
# grab an element from the array ex >> the digit 5
# first passing the row then the column 
arr_2d[0][0]

5

In [65]:
# get back the entire row of index 0 
arr_2d[0]

array([ 5, 10, 15])

In [66]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
# grab the digit 25 
# index 1 for the row and index 1 for the column 
arr_2d[1][1]

25

In [68]:
# fill the brackets to to grab 40
arr_2d[2][1]

40

In [69]:
# another way using common instead of double brackets, 1st for the row 2nd for the column 
arr_2d[1,2]

30

In [70]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [71]:
# grap the whole values of a specific column 
arr_2d[:,1]

array([10, 25, 40])

In [72]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [73]:
# slicing to grab a certain section of a 2D array 
# ex >> let's grab [10, 15],
#                  [25, 30]

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [74]:
# get back all elements from the first 2 rows 
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [75]:
# conditional selection 
arr = np.arange(1,11)

In [76]:
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
# we can take an array combine it with comparison operators and get a full boolean array out of this.
# ex >> 
arr > 5 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [78]:
# save it in a variavble 
bool_arr = arr > 5 

In [79]:
# call it to check 
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [80]:
# now we can use that boolean array to actually index or conditionally select elements 
# from that original array where this happened to be true.

arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [81]:
# do it in one step "more common"
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [82]:
# let's know all the elements in array smaller than 7 
arr[arr < 7]

array([1, 2, 3, 4, 5, 6])

In [83]:
# practice & practice & practice 
# create a 2D array 
arr_2d = np.arange(50).reshape(5,10)

In [84]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [85]:
# grab 13,14 and 23,24 
arr_2d[1:3,3:5]


array([[13, 14],
       [23, 24]])

### NumPy Operations: 

In [86]:
# create an array 
arr = np.arange(0,11)

In [87]:

arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
# perform array with array operations just by using simple arithmetic 
# ex >>  add two arrays together on elements by elements basis you would just array plus array.
# 
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
# same thing for subtraction 
arr - arr  

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
# or multiplication 
arr * arr 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [92]:
# scalar operations
# scalers mean a single number, numpy basically broadcasts that number to every element in the array
# so the operation occurs also on an element by element basis
# ex >> add 100 to each element of the array 
arr + 100 

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [93]:
# or subtract 
arr - 100 

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [94]:
# or square 
arr ** 2 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [95]:
# Universal Array Functions, many mathematical operations.
# use to perform the operation and broadcast across the entire array.
# Let's see common ones.
# ex >> get the square root of an array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [96]:
# get the max value in an array 
np.max(arr)

10

In [97]:
# another way
arr.max()

10

In [98]:
# get the min value in an array 
np.min(arr)

0

In [99]:
# another way
arr.min()

0

In [100]:
# get the mean value 
arr.mean()

5.0

In [101]:
# get the sin value for the elements of an array 
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [102]:
# get the log value for the elements of an array 
np.log(arr)

/var/folders/lv/zk0lzbg140d8fy0bvqcgt_z80000gn/T/ipykernel_96086/4099175084.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [103]:
# make two arrays concatenated in one 
arr_1 = np.array([[1, 2], [3, 4]])
arr_2 = np.array([[6, 7], [8, 9], [10, 11]])

In [104]:
arr_1

array([[1, 2],
       [3, 4]])

In [105]:
arr_2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [106]:
arr_conc = np.concatenate((arr_1, arr_2))

In [107]:
arr_conc

array([[ 1,  2],
       [ 3,  4],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [108]:
# transpose rows and columns 
arr_conc.transpose()

array([[ 1,  3,  6,  8, 10],
       [ 2,  4,  7,  9, 11]])

In [109]:
# see the link of universal functions 
# https://numpy.org/doc/stable/reference/ufuncs.html