# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/michalpasternak/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/michalpasternak/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/michalpasternak/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/michalpasternak/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = ASIMDHP,ASIMD

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(f'The memory size of array zeros would be {x.size * x.itemsize}.')

The memory size of array zeros would be 80.


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
x = np.arange(10,49)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
x = np.flip(x) # version using flip
x

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [10]:
x = np.arange(10,49)
x = x[::-1] # version using indexing
x

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
# version using where
x = np.array([1,2,0,0,4,0])
np.where(x != 0)

(array([0, 1, 4]),)

In [13]:
# version using nonzero
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
x = np.eye(3,3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
# using rand
x = np.random.rand(3,3)
x

array([[0.07450362, 0.97106015, 0.37331927],
       [0.15523509, 0.46822963, 0.01221681],
       [0.5519452 , 0.90536548, 0.82416215]])

In [16]:
# using random. They will both render the same results.
# The difference is in input format (single arg for dimensions (tuple or list) vs a sequence of dimension args)
x = np.random.random((3,3))
x

array([[0.79433327, 0.57402429, 0.54024024],
       [0.15812964, 0.36610128, 0.2342807 ],
       [0.45789343, 0.49650913, 0.97329761]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
x = np.random.rand(10,10)
print(f'min: {x.min()}')
print(f'max: {x.max()}')

min: 0.02048217608940528
max: 0.9910786540206052


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
x = np.random.rand(30)
print(f'mean: {x.mean()}')

mean: 0.4976569283116866


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
# using pad
x = np.zeros((3,3))
x = np.pad(x, pad_width=1, constant_values=1)
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
# using indexing
x = np.ones((5,5))
x[1:-1,1:-1] = 0    # leaves the 1 on the border and changes everything else to 0.
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [21]:
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

In [22]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [23]:
x = np.arange(1,5)
x_diag = np.diag(x, k=-1)
x_diag

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [34]:
# interesting, but a bit complicated
x = np.indices((8,8)).sum(axis=0) % 2
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [25]:
# using indexes ([rows , columns])
x = np.zeros((8,8))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [26]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [27]:
x = np.eye(2,2)
x = np.tile(x, (4,4))
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

22. Normalize a 5x5 random matrix (★☆☆)

In [28]:
# normalize 1D array
array = np.arange(1,10)
arrmax, arrmin = array.max(), array.min()
array = (array - arrmin) / (arrmax - arrmin)
array

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [29]:
# normalize matrix
matrix = np.random.random((5,5))
matmax, matmin = matrix.max(), matrix.min()
matrix = (matrix - matmin) / (matmax - matmin)
matrix

array([[0.11136055, 0.92758481, 0.11197665, 0.134435  , 0.7508849 ],
       [0.18265482, 0.13871108, 0.91556835, 0.71932728, 0.72830727],
       [0.38114221, 0.5704609 , 0.3110254 , 0.55926849, 0.        ],
       [1.        , 0.13180012, 0.47266843, 0.79019779, 0.17058884],
       [0.36746094, 0.85084541, 0.63034228, 0.84994994, 0.93002024]])

In [30]:
# from solutions file
matrix = np.random.random((5,5))
matrix = (matrix - np.mean(matrix)) / (np.std(matrix))
matrix

array([[-0.8158571 ,  0.67629784,  1.83274809, -0.9608307 , -0.47854814],
       [-1.57336577,  1.0368657 , -0.65616386,  0.96406621,  1.61467801],
       [-1.15489801,  0.08913561,  1.41851064, -1.04130304, -0.22262617],
       [-0.21396418, -0.20429996,  1.55172275,  0.01331617, -1.32164312],
       [-0.04714902,  1.15793632, -1.20083656,  0.1038403 , -0.567632  ]])

23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [41]:
x = np.arange(15).reshape(5,3)
print(x)
y = np.arange(6).reshape(3,2)
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]


In [44]:
np.dot(x,y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [63]:
x = np.arange(15)
x[(x>3) & (x<8)] *= -1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

26. What is the output of the following script? (★☆☆)

In [8]:
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10
